int	collide(int, int, int);
void	hold(void);
void	drop(void);
void	gameover(void);
void	step(void);
void	readboard(char*);
void	initgame(void);
void	redraw(void);
void	quit(void);
u64int	nanosec(void);
